export const uniqueCity = [
  { value: "all", label: "All" },
  { value: "colombo", label: "Colombo" },
  { value: "colombo_07", label: "Colombo 07" },
  { value: "kandy", label: "Kandy" },
  { value: "galle", label: "Galle" },
  { value: "matale", label: "Matale" },
  { value: "nuwara_eliya", label: "Nuwara Eliya" },
  { value: "malabe", label: "Malabe" },
  { value: "kiribathgoda", label: "Kiribathgoda" },
  { value: "gonawala", label: "Gonawala" },
  { value: "maharagama", label: "Maharagama" },
  { value: "homagama", label: "Homagama" },
  { value: "angoda", label: "Angoda" },
  { value: "piliyandala", label: "Piliyandala" },
  { value: "battaramulla", label: "Battaramulla" },
  { value: "dehiwala", label: "Dehiwala" },
  { value: "ja_ela", label: "Ja-Ela" },
  { value: "ragama", label: "Ragama" },
  { value: "kadawatha", label: "Kadawatha" },
  { value: "negombo", label: "Negombo" },
  { value: "kelaniya", label: "Kelaniya" },
  { value: "wattala", label: "Wattala" },
  { value: "moratuwa", label: "Moratuwa" },
  { value: "panadura", label: "Panadura" },
  { value: "beruwala", label: "Beruwala" },
  { value: "matara", label: "Matara" },
  { value: "batticaloa", label: "Batticaloa" },
  { value: "anuradhapura", label: "Anuradhapura" },
  { value: "polonnaruwa", label: "Polonnaruwa" },
  { value: "kurunegala", label: "Kurunegala" },
  { value: "chilaw", label: "Chilaw" },
  { value: "puttalam", label: "Puttalam" },
  { value: "hambantota", label: "Hambantota" },
  { value: "ampara", label: "Ampara" },
  { value: "monaragala", label: "Monaragala" },
  { value: "vavuniya", label: "Vavuniya" },
  { value: "jaffna", label: "Jaffna" },
  { value: "trincomalee", label: "Trincomalee" },
  { value: "kalmunai", label: "Kalmunai" },
  { value: "kegalle", label: "Kegalle" },
  { value: "badulla", label: "Badulla" },
  { value: "ratnapura", label: "Ratnapura" },
  { value: "avissawella", label: "Avissawella" },
  { value: "kottawa", label: "Kottawa" },
  { value: "mawanella", label: "Mawanella" },
  { value: "dambulla", label: "Dambulla" },
  { value: "haputale", label: "Haputale" },
  { value: "ella", label: "Ella" },
  { value: "hatton", label: "Hatton" },
  { value: "welimada", label: "Welimada" }
];

export const priceRange = [
  {
    label: "Below LKR 1 Million",
    value: "below-1M",
    min: 0,
    max: 1000000,
  },
  {
    label: "LKR 1M - 5M",
    value: "1M-5M",
    min: 1000000,
    max: 5000000,
  },
  {
    label: "LKR 5M - 10M",
    value: "5M-10M",
    min: 5000000,
    max: 10000000,
  },
  {
    label: "LKR 10M - 25M",
    value: "10M-25M",
    min: 10000000,
    max: 25000000,
  },
  {
    label: "LKR 25M - 50M",
    value: "25M-50M",
    min: 25000000,
    max: 50000000,
  },
  {
    label: "Above LKR 50 Million",
    value: "above-50M",
    min: 50000000,
    max: Infinity,
  },
];
